#the delay for every taxing in seconds.
#10800seconds = 3hours.
delay: 10800

#the time in bukkit-ticks where the timer will update.
#20ticks = 1second
updateRatio: 20

#Tax amount in % from the players balance.
#Min: 1 ; Max: 100
#Set 'taxamountenabled' to true if you want to cut a specific amount.
taxRate: 20.0

#Sets the amount to withdraw from player balances.
#Set 'taxamountenabled' to true if you want to enable this.
taxAmountEnabled: false
taxAmount: 100.0



#DO NOT TOUCH THIS!
currentState: 0
taxTimes: 0